version: '3'

services:
  proxy:
    build:
      context: nginx
      dockerfile: Dockerfile.prod
    container_name: proxy
    ports:
      - 8080:80
    networks:
      - node-network
    depends_on:
      - app

  app:
    build:
      context: node
    container_name: app
    entrypoint:  dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh
    command: node index.js
    tty: true
    networks:
      - node-network
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - node-network
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  node-network:
    driver: bridge
