FROM node:20 as builder

WORKDIR /usr/scr/app

RUN apt-get update && apt-get install -y wget

COPY . .

FROM node:20-alpine3.16

WORKDIR /usr/scr/app
COPY --from=builder /usr/scr/app .
EXPOSE 3000
ENTRYPOINT [ "docker-entrypoint.sh" ]
CMD [ "node", "index.js" ]